### PR TITLE
Multiindex selection

### PR DESCRIPTION
**Pull request by benjamingaudin**
Based on your first point and my comment, I though of the following change

> Alternatively, we could do `mindex{idx,col} --> Index` and `mindex(idx,cols) --> MultiIndex`, which is more consistent but that would break compability with `index(:,1).value --> array`.

The change is the following (adding the mixin RedefinesBrace to Index)

`mindex{idx,col} --> Index`, forcing col to be 1-dimensional; `mindex(idx,cols) --> MultiIndex`. To keep compability with Index, `index(idx) --> Index` and `index{idx} --> Index` return the same thing

so whenever you want an `Index` as output and are unsure of the input class, use `brace`, and when you want to keep the same class, use `paren`

### CODE REVIEW

**Comment by mreijnde** [comment]
Your proposal is improvement with behavior from the other pull request, but find it still bit complex for a user. Specifically as it deviates from the data frame behavior where {} is always position indexing, and () position indexing.  I checked, the current mindex selection behavior is also not consistent with that as mindex(:, dimname) and mindex(:, dimindex) is possible and no indexing with {} is allowed. 

In my view the ideal situation would be that a user should not have to care if it is a Index or MultiIndex. They should behave the same, and far as matlab allowes be a logical extension.  That would makes switching between them easy, ideally even transparant, so a user could use multi dimensional features when that fits without rewriting code. We are not there yet.

I am wondering, where does it all go wrong if you just output MultiIndex (with a single dimension). If it is only the .value, maybe we could also try to fix that.  For example something like:
- mindex.value ==> array(Nelem, Ndim) in case of same data type (error for multiple datatypes)
- mindex.value_cell ==> array(Nelem) of cell(1,Ndim) 

It is unfortunately matlab cannot handle arrays of different datatypes, that would make life easier. Maybe it helps that with the change that df now outputs the index objects directly, the .value is less required.

**Comment by benjamingaudin** [comment]
>mindex.value ==> array(Nelem, Ndim) in case of same data type (error for multiple datatypes)
mindex.value_cell ==> array(Nelem) of cell(1,Ndim)

This could be the solution. They have the same problem with tables, when you try to get the data.
tb{:,:} will try to fit the data in an array, even if it means changing the type of the data inside (ugh..), or fail if the data is "too heterogeneous".

I agree with you that {} is confusing in regards of how it works in the DataFrame. I probably won't include it.

**Comment by benjamingaudin** [comment]
Not sure what you mean by
>In case of an output of array(Nelem,Nind) by .value this does not work. In that case you need to use mindex.value(ind,:).

What I have just implemented gives to tool to the user whether he wants a cell or an array from the mindex
```
mindex.value ==>  array of cells(1,Ndim)
mindex.valueArray ==>  array (Nrows,Ndim)

index.value == index.valueArray
```

**Comment by mreijnde** [comment]
> Not sure what you mean by
> 
> > In case of an output of array(Nelem,Nind) by .value this does not work. In that case you need to use mindex.value(ind,:).

That was a bit cryptic, I try to explain. I was thinking about getting the values for a given index element, in case array is outputted:
r = df.rows.value; % array(Nelem, Ndim)
In case user only uses code with index, it probably writes r(4) to select the 4th index. That can be used as selector as df( r(4) ), 
but in case of multiple dimensions that does not work, as you have to use r(4,:).

What is preferred also depends on what the typical scenarios are for using .value.  But more importantly, I really like solutions where index and mindex behave exactly the same way, especially in case of a single dimension. In that way all code that works with index, should also work for mindex with a single dimension.

In your example there is a difference between index and mindex:
```
index.value  ==>  array (Nrows,1)
mindex.value ==>  array of cells(1,Ndim)

index.valueArray ==>  array (Nrows,1)  
mindex.valueArray ==>  array (Nrows,Ndim)   [[creates error in case of heterogeneous types]]

```

To make mindex and index behave the same I proposed:
```
index.value   ==>  array (Nrows,1)
mindex.value  ==>  array (Nrows,1)         [[ if Ndim==1]]
mindex.value  ==>  array of cells(1,Ndim)  [[ if Ndim>1]]
```
even the data type changes in case of added dimensions, indexing the array using just r(ind) works. And the result can be used for indexing. For me this I think best solution, and prevents differences, and supports hetrogeneous types.

additionally the 2 other value variants can I think be of use, depending on exactly where you want to use the value for:
```
index.valueArray ==>  array (Nrows,1)  
mindex.valueArray ==>  array (Nrows,Ndim)   [[creates error in case of heterogeneous types]]
```
as you now have implemented


and additionally:
```
index.valueCell   ==>  array of cells(1,1) 
mindex.valueCell  ==>  array of cells(1,Ndim) 
```
for cases it is handier that data type stays exactly the same.


By making the best choice, I hope it becomes easier to get all the existing functionality work with multi index without much extra effort.

**Comment by benjamingaudin** [comment]
>In case user only uses code with index, it probably writes r(4) to select the 4th index. That can be used as selector as df( r(4) ), but in case of multiple dimensions that does not work, as you have to use r(4,:).

You can use mindex(4) to select the 4th row of the multiindex if I understand what you mean here.

-----------------------------------------------


```
mindex.value  ==>  array (Nrows,1)         [[ if Ndim==1]]
mindex.value  ==>  array of cells(1,Ndim)  [[ if Ndim>1]]
```
Would be the best solution with a language that understand the difference between a scalar and a 1-dimensional array. Unfortunately Matlab does not.

The output of 
```
mindex(1:nselect).value
```
would differ if nselect==1 or if nselect > 1. It is dangerous not to be able to control the type of the output. I would not recommend it.

**Comment by mreijnde** [comment]
I understand, all solutions have there quirks due to limitations of matlab. You have make a choice on what the worst behavior is.

Let's take example `idx = frames.MultiIndex({{1,"A",11},{2,"B",22},{3,"C",33}}, name=["x","y","z"])`.

Some ideas on .valueArray with mindex behavior:
- as mentioned in code comments, I don't like the auto type conversion, let's throw errors.
   - idx.valueArray ==> error
   - idx.valueArray(:,1) ==> error     % workaround idx(:,1).valueArray
   - idx.valueArray(:,[1 3]) ==> error  % workaround idx(:,[1 3]).valueArray


- possible enhancement, using matlab.mixin.indexing.RedefinesDot it is possible to allow those cases to work without workaround:
   - idx.valueArray ==> error
   - idx.valueArray(:,1) ==> array
   - idx.valueArray(:,[1 3]) ==> array

This is nicer syntax if you try to get to values per dimension.

**Comment by benjamingaudin** [comment]
Let's throw an error when the types are different then, as in your first suggestion.

I'm not a fan of the second proposition. It feels counter-intuitive that the validity of the property depends on what part you try to access.
If `res = idx.valueArray(:,1)` works, then `tmp = idx.valueArray; res = tmp(:,1)` should work.

**Pull request merged**
